variables:
    AUDIT_AWS_CLOUDTRAIL_ALERT_LIST:
        description: "Which alerts would you like to check for? (Default is all Cloudtrail alerts)"
        required: true
        type: array
        default:
            - cloudtrail-service-disabled
    AUDIT_AWS_CLOUDTRAIL_ALLOW_EMPTY:
        description: "Would you like to receive empty reports? Options - true / false. Default is false."
        required: true
        type: boolean
        default: false
    AUDIT_AWS_CLOUDTRAIL_SEND_ON:
        description: "Send reports always or only when there is a change? Options - always / change. Default is change."
        required: true
        type: string
        default: "change"
    AUDIT_AWS_CLOUDTRAIL_ALERT_RECIPIENT:
        description: "Enter the email address(es) that will receive notifications. If more than one, separate each with a comma."
        required: true
        type: string
        default: null
    AUDIT_AWS_CLOUDTRAIL_REGIONS:
        description: "List of AWS regions to check. Default is us-east-1,us-west-1,us-west-2."
        required: true
        type: array
        default:
            - us-east-1
            - us-west-1
            - us-west-2
